[package]
name = "duke"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
dotenv = "0.15"

[[bin]]
name = "duke"
path = "src/main.rs"
